### PR TITLE
Changed carousel images, copyright, YouTube embed

### PR DESCRIPTION
**Pull request by athityakumar**

### CODE REVIEW

**Comment by athityakumar** [comment]
Demo : https://athityakumar.github.io/auviitkgp.github.io/
Ping @icyflame @kshitijgoel007

**Comment by icyflame** [comment]
@athityakumar Add appropriate captions on the images that are there on the homepage. Rest LGTM.

**Comment by athityakumar** [comment]
@icyflame - Done. Also, I slightly changed the styling of the carousel. :smile:

**Comment by athityakumar** [comment]
Are there any changes required in the teams page? Any new members to be added or old ones to be removed?

**Comment by icyflame** [comment]
@athityakumar not now.

**Pull request merged**
