### PR TITLE
Make the two navbar.html files identical

### PR DESCRIPTION
**Pull request by icyflame**
- Change the path of the image to refer it from root (/) of the site
- Change the path of the home page of the site to the root (/) of the
site
- Change all relative paths to start from the root of the site.
- By making all the paths from the root of the site, the two navbar.html files may be made identical without breaking anything else.

### CODE REVIEW

**Comment by routeaccess** [comment]
- Please add a leading `/` to `href` attribute in line numbers 25 and 27. 
- Also, please edit the commit message header to mention the modification of path references to relative-to-website-root rather than 'making navbars identical' - more useful history.
- The 3 points of details of commit message looks redundant and near-identical. Consider summarising in a line.

**Comment by icyflame** [comment]
In the spirit of keeping the master clean, I have opened a new PR #12.

**Comment by routeaccess** [comment]
@icyflame You trick me once, shame on you, you trick me twice, shame on me. Please not again, soldier. :stuck_out_tongue:

**Comment by icyflame** [comment]
You should have raised the fact about me sending a PR from master as soon as you saw the PR! :stuck_out_tongue:

**Comment by routeaccess** [comment]
:sweat_smile:

**Pull request closed without merging**
